package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Qa'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Qa")) {
    expectDisabledSettings("RUNNER_6")
    updateDisabledSettings("RUNNER_26", "RUNNER_6")
}
