package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Test'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Test")) {
    params {
        add {
            param("env.admin_users", "aa bb cc a9k47zz")
        }
        add {
            param("env.cnjbossprod01_user", "carl2222")
        }
    }

    expectSteps {
        script {
            name = "test_multiline_script"
            scriptContent = "echo %teamcity.build.triggeredBy%"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            scriptContent = """
                echo %env.admin_users%
                echo ${'$'}{admin_users}
                
                for i in ${'$'}{admin_users[@]};
                do 
                  echo ${'$'}i;
                  if [ "%teamcity.build.triggeredBy.username%" == ${'$'}i ];then 
                    echo ok;
                    break;
                  fi;
                done
            """.trimIndent()
        }
    }
}
