package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    expectDefaultTemplate(AbsoluteId("CarlTest_BeforeScript"))
    defaultTemplate = null

    params {
        add {
            text("env.admin_users", "aa bb", readOnly = true, allowEmpty = false)
        }
    }

    expectBuildTypesOrder(RelativeId("Build1"), RelativeId("Qa"), RelativeId("Prod"))
    buildTypesOrderIds = arrayListOf(RelativeId("Build1"))
}
